### ISSUE TITLE
[Insight] Missing use statement should be avoided - in src/…/implementations/view-factory.php, line 82

### ISSUE THREAD

**Issue by rraub** [asu-ke-web-services/nectary#47]
**[in src/factories/implementations/view-factory.php, line 82](https://github.com/gios-asu/nectary/blob/95f9daac4169367631f372cbb4b9a55d6837f54e/src/factories/implementations/view-factory.php#L82)**

> The `Viewable_Model` class resolves to the `Nectary\Factories\Viewable_Model` class which PHP does not seem to be able to autoload.

``` php
   */
  public function add_data( $data ) {
    if ( is_array( $data ) ) {
      foreach ( $data as $key => $value ) {
        $data_to_add = null;
        if ( $value instanceof Viewable_Model ) {
          $data_to_add = $value->present();
        } else if ( is_object( $value ) ) {
          $data_to_add = json_decode( json_encode( $value ), true );
        } else {
          $data_to_add = $value;
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c2a77155-dba1-4928-8f87-25bc2f0c869e/analyses/1)_

**Comment by idmontie** [comment]
That has already been fixed in the develop branch.
