### ISSUE TITLE
Use an HTML Tidy package thats available via composer 

### ISSUE THREAD

**Issue by rraub** [asu-ke-web-services/nectary#5]
It will make this framework more portable. 

However no alternatives stand out to me currently. 
https://github.com/kesar/HTMLawed might we worth looking into, but thats some of the grosses code I've seen in a while.

**Comment by idmontie** [comment]
We can maybe fork it and make it another composer package. Maybe call it Bee_Keeper.

**Comment by rraub** [comment]
WordPress doesn't even do this right: https://codex.wordpress.org/Function_Reference/get_the_excerpt

**Comment by idmontie** [comment]
We can use PHP_Humanizer once [this pull request](https://github.com/coduo/php-humanizer/pull/30) gets merged in.

**Comment by rraub** [comment]
:+1: :bear:

**Comment by idmontie** [comment]
They merged the branch in, just waiting for a new Release.

**Comment by idmontie** [comment]
Waiting for version 1.0.8.

**Comment by idmontie** [comment]
Version 1.0.9 is out! Starting this now!

**Comment by idmontie** [comment]
Ugh, we have to wait for 2.0.0 or a bump above 1.0.9 for PHP 7 compliance.

**Comment by idmontie** [comment]
Waiting on https://github.com/coduo/php-humanizer/issues/77

**Comment by idmontie** [comment]
Will have to completely rewrite the "tidy_service" code.

**Comment by idmontie** [comment]
Also, no longer waiting on php-humanizer, there is a pre-release that we can use for PHP7: https://github.com/coduo/php-humanizer/releases/tag/2.0.0-beta

**Comment by rraub** [comment]
:sunglasses:
